"""Seed Helm with realistic demo data for all 8 product feeds."""
from django.core.management.base import BaseCommand
from django.utils import timezone

from dashboard.models import CachedFeedSnapshot


DEMO_FEEDS = {
    'harbor': {
        'product': 'harbor',
        'product_label': 'Harbor',
        'product_url': 'https://harbor.docklabs.ai',
        'metrics': [
            {
                'key': 'active_grants',
                'label': 'Active Grants',
                'value': 47,
                'unit': None,
                'trend': 'up',
                'trend_value': 3,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://harbor.docklabs.ai/grants/?status=active',
            },
            {
                'key': 'ytd_disbursed',
                'label': 'YTD Disbursed',
                'value': 42750000,
                'unit': 'USD',
                'trend': 'up',
                'trend_value': 8200000,
                'trend_period': 'quarter',
                'severity': 'normal',
                'deep_link': 'https://harbor.docklabs.ai/reports/disbursements/',
            },
            {
                'key': 'pipeline_count',
                'label': 'In Pipeline',
                'value': 12,
                'unit': None,
                'trend': 'flat',
                'trend_value': 0,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://harbor.docklabs.ai/applications/',
            },
        ],
        'action_items': [
            {
                'id': 'harbor-grant-review-1234',
                'type': 'review',
                'title': 'Review: Small Business Express - Acme Corp',
                'description': 'Grant application pending program director review',
                'priority': 'high',
                'due_date': '2026-04-05',
                'assigned_to_role': 'program_director',
                'deep_link': 'https://harbor.docklabs.ai/grants/1234/review/',
                'created_at': '2026-03-28T10:00:00Z',
            },
            {
                'id': 'harbor-grant-review-1235',
                'type': 'approval',
                'title': 'Approve: MAA Phase II - Sikorsky',
                'description': 'Final approval for $2.4M manufacturing grant',
                'priority': 'medium',
                'due_date': '2026-04-08',
                'assigned_to_role': 'program_director',
                'deep_link': 'https://harbor.docklabs.ai/grants/1235/review/',
                'created_at': '2026-03-30T14:00:00Z',
            },
        ],
        'alerts': [
            {
                'id': 'harbor-compliance-overdue-5678',
                'type': 'overdue',
                'title': 'Quarterly report overdue: MAA - Sikorsky (15 days)',
                'severity': 'warning',
                'since': '2026-03-15',
                'deep_link': 'https://harbor.docklabs.ai/compliance/5678/',
            },
        ],
        'sparklines': {
            'active_grants': {
                'values': [42, 43, 44, 44, 45, 45, 46, 46, 46, 47, 47, 47],
                'labels': ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
                'period': 'month',
            },
        },
    },
    'bounty': {
        'product': 'bounty',
        'product_label': 'Bounty',
        'product_url': 'https://bounty.docklabs.ai',
        'metrics': [
            {
                'key': 'opportunities_tracked',
                'label': 'Tracked',
                'value': 12,
                'unit': None,
                'trend': 'up',
                'trend_value': 2,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://bounty.docklabs.ai/opportunities/',
            },
            {
                'key': 'submissions_pending',
                'label': 'Pending Submissions',
                'value': 3,
                'unit': None,
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'normal',
                'deep_link': 'https://bounty.docklabs.ai/submissions/',
            },
            {
                'key': 'awards_received',
                'label': 'Awards This FY',
                'value': 5,
                'unit': None,
                'trend': 'up',
                'trend_value': 2,
                'trend_period': 'quarter',
                'severity': 'normal',
                'deep_link': 'https://bounty.docklabs.ai/awards/',
            },
        ],
        'action_items': [
            {
                'id': 'bounty-submission-2001',
                'type': 'submission',
                'title': 'Submit: DOC EDA Infrastructure Grant',
                'description': 'Federal application deadline approaching',
                'priority': 'high',
                'due_date': '2026-04-10',
                'assigned_to_role': 'federal_coordinator',
                'deep_link': 'https://bounty.docklabs.ai/opportunities/2001/submit/',
                'created_at': '2026-03-25T09:00:00Z',
            },
        ],
        'alerts': [],
        'sparklines': {},
    },
    'beacon': {
        'product': 'beacon',
        'product_label': 'Beacon',
        'product_url': 'https://beacon.docklabs.ai',
        'metrics': [
            {
                'key': 'active_companies',
                'label': 'Active Companies',
                'value': 284,
                'unit': None,
                'trend': 'up',
                'trend_value': 18,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://beacon.docklabs.ai/companies/',
            },
            {
                'key': 'interactions_this_month',
                'label': 'Interactions',
                'value': 67,
                'unit': None,
                'trend': 'up',
                'trend_value': 12,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://beacon.docklabs.ai/interactions/',
            },
            {
                'key': 'pipeline_value',
                'label': 'Pipeline Value',
                'value': 15800000,
                'unit': 'USD',
                'trend': 'up',
                'trend_value': 3200000,
                'trend_period': 'quarter',
                'severity': 'normal',
                'deep_link': 'https://beacon.docklabs.ai/pipeline/',
            },
        ],
        'action_items': [],
        'alerts': [],
        'sparklines': {
            'active_companies': {
                'values': [245, 250, 255, 258, 262, 265, 268, 272, 275, 278, 281, 284],
                'labels': ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
                'period': 'month',
            },
        },
    },
    'admiralty': {
        'product': 'admiralty',
        'product_label': 'Admiralty',
        'product_url': 'https://admiralty.docklabs.ai',
        'metrics': [
            {
                'key': 'open_requests',
                'label': 'Open Requests',
                'value': 8,
                'unit': None,
                'trend': 'down',
                'trend_value': 2,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://admiralty.docklabs.ai/requests/',
            },
            {
                'key': 'avg_response_time',
                'label': 'Avg Response',
                'value': 4.2,
                'unit': 'days',
                'trend': 'down',
                'trend_value': 0.8,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://admiralty.docklabs.ai/reports/',
            },
            {
                'key': 'overdue_requests',
                'label': 'Overdue',
                'value': 1,
                'unit': None,
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'warning',
                'deep_link': 'https://admiralty.docklabs.ai/requests/?status=overdue',
            },
        ],
        'action_items': [
            {
                'id': 'admiralty-response-2047',
                'type': 'response',
                'title': 'Respond: FOIA #2024-47 (Hartford Courant)',
                'description': 'Response deadline approaching',
                'priority': 'high',
                'due_date': '2026-04-04',
                'assigned_to_role': 'foia_officer',
                'deep_link': 'https://admiralty.docklabs.ai/requests/2047/respond/',
                'created_at': '2026-03-20T11:00:00Z',
            },
        ],
        'alerts': [],
        'sparklines': {},
    },
    'manifest': {
        'product': 'manifest',
        'product_label': 'Manifest',
        'product_url': 'https://manifest.docklabs.ai',
        'metrics': [
            {
                'key': 'pending_signatures',
                'label': 'Pending Signatures',
                'value': 5,
                'unit': None,
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'normal',
                'deep_link': 'https://manifest.docklabs.ai/queue/',
            },
            {
                'key': 'avg_turnaround',
                'label': 'Avg Turnaround',
                'value': 2.1,
                'unit': 'days',
                'trend': 'down',
                'trend_value': 0.3,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://manifest.docklabs.ai/reports/',
            },
            {
                'key': 'signed_this_month',
                'label': 'Signed This Month',
                'value': 14,
                'unit': None,
                'trend': 'up',
                'trend_value': 3,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://manifest.docklabs.ai/completed/',
            },
        ],
        'action_items': [
            {
                'id': 'manifest-sign-3001',
                'type': 'signature',
                'title': 'Sign: March Close Package',
                'description': 'Monthly close package awaiting commissioner signature',
                'priority': 'high',
                'due_date': '2026-04-03',
                'assigned_to_role': 'executive',
                'deep_link': 'https://manifest.docklabs.ai/packets/3001/sign/',
                'created_at': '2026-04-01T08:00:00Z',
            },
        ],
        'alerts': [],
        'sparklines': {},
    },
    'lookout': {
        'product': 'lookout',
        'product_label': 'Lookout',
        'product_url': 'https://lookout.docklabs.ai',
        'metrics': [
            {
                'key': 'bills_tracked',
                'label': 'Bills Tracked',
                'value': 23,
                'unit': None,
                'trend': 'up',
                'trend_value': 4,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://lookout.docklabs.ai/bills/',
            },
            {
                'key': 'upcoming_votes',
                'label': 'Votes This Week',
                'value': 2,
                'unit': None,
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'warning',
                'deep_link': 'https://lookout.docklabs.ai/calendar/',
            },
            {
                'key': 'new_amendments',
                'label': 'New Amendments',
                'value': 6,
                'unit': None,
                'trend': 'up',
                'trend_value': 3,
                'trend_period': 'week',
                'severity': 'normal',
                'deep_link': 'https://lookout.docklabs.ai/amendments/',
            },
        ],
        'action_items': [],
        'alerts': [
            {
                'id': 'lookout-vote-sb5',
                'type': 'deadline',
                'title': 'SB-5: Committee vote tomorrow',
                'severity': 'warning',
                'since': '',
                'deep_link': 'https://lookout.docklabs.ai/bills/sb5/',
            },
        ],
        'sparklines': {},
    },
    'purser': {
        'product': 'purser',
        'product_label': 'Purser',
        'product_url': 'https://purser.docklabs.ai',
        'metrics': [
            {
                'key': 'close_progress',
                'label': 'Close Progress',
                'value': 60,
                'unit': 'percent',
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'normal',
                'deep_link': 'https://purser.docklabs.ai/close/',
            },
            {
                'key': 'period_disbursed',
                'label': 'Period Disbursed',
                'value': 5420000,
                'unit': 'USD',
                'trend': 'up',
                'trend_value': 820000,
                'trend_period': 'month',
                'severity': 'normal',
                'deep_link': 'https://purser.docklabs.ai/disbursements/',
            },
            {
                'key': 'variance_flags',
                'label': 'Variance Flags',
                'value': 2,
                'unit': None,
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'warning',
                'deep_link': 'https://purser.docklabs.ai/variances/',
            },
        ],
        'action_items': [
            {
                'id': 'purser-close-approve-4001',
                'type': 'approval',
                'title': 'Approve: SBE Program March Close',
                'description': 'Program submission ready for review',
                'priority': 'medium',
                'due_date': '2026-04-07',
                'assigned_to_role': 'program_director',
                'deep_link': 'https://purser.docklabs.ai/close/4001/review/',
                'created_at': '2026-04-01T12:00:00Z',
            },
        ],
        'alerts': [
            {
                'id': 'purser-variance-9001',
                'type': 'variance',
                'title': 'Budget variance >10%: MAA Program',
                'severity': 'warning',
                'since': '2026-03-28',
                'deep_link': 'https://purser.docklabs.ai/variances/9001/',
            },
        ],
        'sparklines': {
            'close_progress': {
                'values': [0, 0, 10, 20, 30, 35, 40, 45, 50, 55, 58, 60],
                'labels': ['W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W7', 'W8', 'W9', 'W10', 'W11', 'W12'],
                'period': 'week',
            },
        },
    },
    'yeoman': {
        'product': 'yeoman',
        'product_label': 'Yeoman',
        'product_url': 'https://yeoman.docklabs.ai',
        'metrics': [
            {
                'key': 'pending_invitations',
                'label': 'Pending Invitations',
                'value': 4,
                'unit': None,
                'trend': None,
                'trend_value': None,
                'trend_period': None,
                'severity': 'normal',
                'deep_link': 'https://yeoman.docklabs.ai/invitations/',
            },
            {
                'key': 'meetings_this_week',
                'label': 'Meetings This Week',
                'value': 11,
                'unit': None,
                'trend': 'up',
                'trend_value': 3,
                'trend_period': 'week',
                'severity': 'normal',
                'deep_link': 'https://yeoman.docklabs.ai/calendar/',
            },
            {
                'key': 'triage_backlog',
                'label': 'Triage Backlog',
                'value': 2,
                'unit': None,
                'trend': 'down',
                'trend_value': 1,
                'trend_period': 'week',
                'severity': 'normal',
                'deep_link': 'https://yeoman.docklabs.ai/triage/',
            },
        ],
        'action_items': [],
        'alerts': [],
        'sparklines': {},
    },
}


class Command(BaseCommand):
    help = 'Seed Helm with demo product feed data for all 8 fleet products'

    def handle(self, *args, **options):
        now = timezone.now()
        created = 0
        updated = 0

        for product_key, feed_data in DEMO_FEEDS.items():
            feed_data['updated_at'] = now.isoformat()

            snapshot, was_created = CachedFeedSnapshot.objects.update_or_create(
                product=product_key,
                defaults={
                    'feed_data': feed_data,
                    'fetched_at': now,
                    'fetch_duration_ms': 42,
                    'is_stale': False,
                    'last_error': '',
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created} new + {updated} updated feed snapshots '
            f'for {len(DEMO_FEEDS)} products.'
        ))
