# Generated by Django 6.0.3 on 2026-04-25 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm_core', '0003_notificationpreference_channel_boswell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOIAExportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_product', models.CharField(db_index=True, max_length=50)),
                ('record_type', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 hash for deduplication.', max_length=64)),
                ('created_by_name', models.CharField(blank=True, max_length=200)),
                ('record_created_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_from_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the staff member who submitted this export.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('foia_request_id_ref', models.CharField(blank=True, db_index=True, help_text='FK reference to FOIARequest in Admiralty (stored as string to avoid cross-DB FK).', max_length=200)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('responsive', 'Responsive'), ('not_responsive', 'Not Responsive'), ('partial', 'Partially Responsive'), ('exempt', 'Exempt')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_foia_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'helm_foia_export_item',
                'ordering': ['-submitted_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['source_product', 'record_type'], name='helm_foia_e_source__dcfbbc_idx'), models.Index(fields=['review_status'], name='helm_foia_e_review__e70a88_idx'), models.Index(fields=['content_hash'], name='helm_foia_e_content_045eae_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_product', 'record_type', 'record_id', 'foia_request_id_ref'), name='helm_core_unique_foia_export')],
            },
        ),
    ]
