# Generated by Django 6.0.3 on 2026-04-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfeedsnapshot',
            name='circuit_open_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedfeedsnapshot',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
    ]
