# Generated by Django 6.0.3 on 2026-04-25 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_task_public_ids(apps, schema_editor):
    """Backfill a fresh UUID per task row before the unique constraint is added.

    Same trap as Project.public_id in 0003 — ``AddField(default=uuid.uuid4)``
    evaluates the callable once at column add time, so every existing row
    inherits the SAME default UUID. We overwrite every row with a fresh
    UUID before ``unique=True`` is enforced.
    """
    Task = apps.get_model('helm_tasks', 'Task')
    for t in Task.objects.all():
        t.public_id = uuid.uuid4()
        t.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('helm_tasks', '0003_project_lifecycle_baseline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProjectRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_description', models.TextField(blank=True)),
                ('retention_policy', models.CharField(choices=[('standard', 'Standard (7 years)'), ('extended', 'Extended (10 years)'), ('permanent', 'Permanent')], default='standard', max_length=15)),
                ('original_created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_purged', models.BooleanField(default=False)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-archived_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('claimed', 'Self-claimed'), ('manager_assigned', 'Manager-assigned')], default='claimed', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('reassigned', 'Reassigned'), ('released', 'Released back to pool')], default='assigned', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-claimed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('external', 'External (applicant-visible)'), ('internal', 'Internal (staff-only)')], default='internal', max_length=10)),
                ('source', models.CharField(choices=[('upload', 'Manually uploaded'), ('manifest_signed', 'Signed document returned from Manifest'), ('system', 'System-generated')], default='upload', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_packet_uuid', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Set for external invites.', max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='contributor', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_on_notes', models.BooleanField(default=True)),
                ('notify_on_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-invited_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='If True, only visible to staff. If False, visible to external users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='helm_tasks__status_e40e98_idx',
            old_name='helm_tasks_status_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='helm_tasks__kind_b3e8c7_idx',
            old_name='helm_tasks_kind_status_idx',
        ),
        # ``Project.archived`` BooleanField removed: ``ArchivableMixin.is_archived``
        # (delegating to ``archived_at``) replaces it. The two-deploy split
        # described in plan §16.2 was designed for rolling deploys; Helm
        # auto-deploys as a single service, so collapsing to one deploy is
        # safer than leaving an orphaned NOT NULL column with no DB default.
        migrations.RemoveField(
            model_name='project',
            name='archived',
        ),
        migrations.AddField(
            model_name='task',
            name='last_due_soon_notif_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_overdue_notif_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Task.public_id — staged add to avoid the unique-callable-default trap
        # (see populate_task_public_ids docstring above).
        migrations.AddField(
            model_name='task',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_task_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='archivedprojectrecord',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Manager who made the assignment; null for self-claims.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_delegated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='helm_tasks.project'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helm_tasks.project'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcollaborator',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcollaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='helm_tasks.project'),
        ),
        migrations.AddField(
            model_name='projectcollaborator',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal user; null for external email invites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='helm_tasks.project'),
        ),
        migrations.AddField(
            model_name='projectstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectstatushistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='helm_tasks.project'),
        ),
        migrations.AddField(
            model_name='taskstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatushistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='helm_tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcollaborator',
            unique_together={('project', 'email'), ('project', 'user')},
        ),
    ]
