# Generated by Django 6.0.3 on 2026-04-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm_tasks', '0004_project_satellites_and_task_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foia_jurisdiction',
            field=models.CharField(blank=True, choices=[('federal', 'Federal (5 USC 552 — 20 business days)')], default='federal', help_text='Jurisdiction whose statutory deadline applies. Federal default.', max_length=24),
        ),
        migrations.AddField(
            model_name='project',
            name='foia_received_at',
            field=models.DateField(blank=True, help_text='Date the FOIA request was received. Triggers the clock.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='foia_statutory_deadline_at',
            field=models.DateField(blank=True, db_index=True, help_text='Computed statutory deadline. Recomputed when received_at, jurisdiction, or tolling changes.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='foia_tolled_at',
            field=models.DateField(blank=True, help_text='Date the clock was paused (tolled).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='foia_tolled_until',
            field=models.DateField(blank=True, help_text='Date the tolling ends and the clock resumes.', null=True),
        ),
    ]
