# Generated by Django 6.0.3 on 2026-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm_tasks', '0005_foia_statutory_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fund_sources',
            field=models.JSONField(blank=True, default=list, help_text='List of {source, amount_cents, label} dicts. Source is from FundSource.'),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_baba',
            field=models.BooleanField(default=False, help_text='Build America, Buy America domestic-procurement requirements apply.'),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_davis_bacon',
            field=models.BooleanField(default=False, help_text='Davis-Bacon Act prevailing wage requirements apply (federal construction).'),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_environmental_review',
            field=models.BooleanField(default=False, help_text='State or local environmental review required.'),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_nepa',
            field=models.BooleanField(default=False, help_text='NEPA environmental review required (federal funds + ground disturbance).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('foia', 'FOIA Request'), ('cip', 'Capital Improvement Plan')], db_index=True, default='standard', max_length=16),
        ),
    ]
