# Generated by Django 6.0.3 on 2026-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm_tasks', '0006_cip_project_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', help_text='Public projects render at /p/<public_id>/ to unauthenticated visitors.', max_length=10),
        ),
    ]
