# Generated by Django 6.0.3 on 2026-04-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helm_tasks', '0007_public_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foia_jurisdiction',
            field=models.CharField(blank=True, choices=[('connecticut', 'Connecticut (CGS §1-206 — 4 business days to acknowledge)'), ('federal', 'Federal (5 USC 552 — 20 business days)')], default='connecticut', help_text='Jurisdiction whose statutory deadline applies. Connecticut default (DECD posture).', max_length=24),
        ),
    ]
